### PR TITLE
Rfdocs 02

### PR DESCRIPTION
**Pull request by andriyko**
Update plugin to work with updated rfdocs.org

### CODE REVIEW

**Comment by andriyko** [comment]
@aaltat

**Comment by aaltat** [comment]
Why did yo change in ```rfassistant/__init__.py``` to ```rfdocs_update_url = "http://127.0.0.1:8000/api/v1/"```

**Comment by aaltat** [comment]
Hmmm, could it be that the setting file: 
```
"rfdocs_update_url": "http://rfdocs.org/dataset/download?",
```
is not actually used?

**Comment by andriyko** [comment]
@aaltat , thank you. Please see https://github.com/andriyko/sublime-robot-framework-assistant/pull/36

**Comment by aaltat** [comment]
I see, thanks from update.

Is the setting file: 
```
"rfdocs_update_url": "http://rfdocs.org/dataset/download?",
```

then not used?

**Comment by andriyko** [comment]
@aaltat The options from settings files are used. All the data is fetched from API. Now the API on rfdocs.org is open. It is here: http://rfdocs.org/api/v1/ (will add more instruction how to use it and how to build queries).
Please note that manifest downloader does not handle error responses correctly (404, etc), so if you define some another valid url for  `rfdocs_update_url` eg : "http://rfdocs.org/api/babar" it will pass silently.
Also I am going to put rfdocs.org source code soon. I think it will be here https://github.com/andriyko/rfdocs.

**Comment by aaltat** [comment]
I understand and thanks from explanation.

**Pull request merged**
