### PR TITLE
futurize to support py3 as well as fix some minor issues

### PR DESCRIPTION
**Pull request by idxn**

### CODE REVIEW

**Comment by aaltat** [comment]
This PR breaks all tests that plugin has, therefore it needs some work.

**Comment by idxn** [comment]
Yep, i'm working on it. I just did a manual test and hope it would pass the all the test but it's not :(

**Comment by idxn** [comment]
I decided to close this and will support only py3. It is too much effort to maintain both.

**Comment by aaltat** [comment]
Support for both is possible, although I agree that I don't know it good effort to support Python 2 when Python 2 end of life is coming quite fast. Perhaps it's best to follow the path that SeleniumLibrary and announce also for this project that Python 2 support is fading away. Unless someone feels that she/he needs it to needs it so much that is filling to contribute.

**Comment by idxn** [comment]
Yeah, I think so. It's the reason I think we should drop the py2 support and support only py3 going forward.

**Pull request closed without merging**
