### PR TITLE
Changes on context menu

### LINKED ISSUE #227: The package path in the Context.sublime-menu file is inconsistent with the actual path
The path to the package in the Context.sublime-menu file is `...Packages/Robot Framework Assistant/...`, 
but the directory that is actually created automatically on my computer is `...Packages/RobotFrameworkAssistant/...` .
I want to understand what caused this difference. This difference cause certain features in the context to not work properly.

### PR DESCRIPTION
**Pull request by idxn**
- Fix #227 
- Update snippets

### CODE REVIEW

**Comment by idxn** [comment]
@andriyko Please provide any feedback you may have. If there is no any comment, please merge this.

**Comment by andriyko** [comment]
The change looks good to me. @aaltat , I would like to merge this PR. Could you please take a look at this as well?

**Comment by aaltat** [comment]
Well, that is a very good question. I don't have the time to maintain this project, unfortunately, but true. SeleniumLibrary eats all my time reserved for doing open source projects. Although I do care about this project, my main focus is in SeleniumLibrary.

Therefore I would be happy to give this project responsibility to someone else. Would anyone of you two willing to take the responsibility? I can, if needed, explain the architecture and deeper design principles to the next maintainer (and shead light to the dark corners, there are few design things which I am not proud of.) Also I am not going anywhere from the Robot Framework ecosystem, I am around to answer questions also after the transfer.

**Comment by idxn** [comment]
I'm happy to keep this plugin alive though. It's the best plugin comparing to the others out there in vscode or pycharm. However, my python knowledge is quite limited and may not be enough to be the maintainer.

**Comment by andriyko** [comment]
@idxn , thank you for your contribution 👍 . 

@aaltat , thank you for the great work done on this project 💯

**Comment by aaltat** [comment]
Well @idxn we could have few sessions about the plugin architecture. But before doing that you could look at Sublime plugin API https://www.sublimetext.com/docs/3/api_reference.html and http://docs.sublimetext.info/en/latest/extensibility/plugins.html After that we could discuss about this plugin itself. Are you in Slack?

**Comment by idxn** [comment]
@aaltat I have only my work slack tanakiat at central.tech

**Comment by aaltat** [comment]
Robot Framework community has also Slack in use, would it be possible to see also there? If yes, please see more details in contact section in https://github.com/robotframework/robotframework/blob/master/README.rst#support-and-contact for how to join.

**Pull request merged**
