### PR TITLE
Integrate rflint with assistant and provide git supports

### PR DESCRIPTION
**Pull request by aaltat**
This pull request fulfills the issue #28 and #26 needs.

### CODE REVIEW

**Comment by aaltat** [comment]
The documentation should be updated and is not part of this pull request. If this is accepted, any comments where I should write the documentation? In the README.md?

**Comment by andriyko** [comment]
@aaltat , please update docs (README.md) within this PR. Also could you please put some screenshots here of what is done?

**Comment by aaltat** [comment]
I will try to a range that as soon as possible.

**Comment by aaltat** [comment]
I made two gif animations: 

rflint-open-tab
rflint-git

**Comment by andriyko** [comment]
Great! Nice feature. What version of Sublime do you use? 3? Could you please ensure that it works with Sublime Text 2?

**Comment by andriyko** [comment]
@aaltat , thanks for your efforts and contributions!

**Comment by aaltat** [comment]
I use Sublime 3. I can check that it works with Sublime 2. 

I will update the issues.

Should I make a pull request that removes the commit: 4f7ef27822a056fe846dfad72421fefaa3a6d95b ?

**Comment by andriyko** [comment]
I think - yes. Having rflint in several places is confusing. It should be removed from build system.

**Comment by aaltat** [comment]
Sorry that it did took so long but I did has terrible flu. 

In any case, plugin works with sublime 2

**Pull request merged**
